/**
 * Source-registry — deklarativ lista över alla eventkällor.
 *
 * ─── PROBE-RESULTAT 2026-06-01 ────────────────────────────────────────────
 * 58 kommuner probade. 7 träffar — men VIKTIG SKILLNAD MELLAN varianter:
 *
 *   ✅ Tribe (The Events Calendar): har start_date/end_date som riktiga
 *      event-datum. Användbar direkt.
 *
 *   ❌ wp/v2/event (eller /evenemang): exponerar bara WP:s publication date,
 *      INTE event-startdatum. Datum ligger i fritext i content.rendered eller
 *      i ACF-fält som inte är publika i REST. Kräver html-cheerio på
 *      detaljsidan ELLER content.rendered-parsing innan den är användbar.
 *
 * Aktiverade (Tribe):       1 källa,   ~48 events
 * Avstängda (wp/v2):        6 källor, ~1864 events — väntar på datum-extraktor
 * ─────────────────────────────────────────────────────────────────────────
 */

import { Source } from './types';

export const SOURCES: Source[] = [
    // ─── WP-REST KOMMUNER (auto-upptäckta via probe-wp) ──────────────────────

    // ─── VENUES (dedikerade event-sitemaps, JSON-LD Event) ──────────────────
    {
        id: 'cirkus',
        hostName: 'Cirkus Stockholm',
        region: 'stockholm',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://cirkus.se/sitemap-events.xml',
            // Bara svenska event-URLs (/sv/evenemang/...), inte /en/shows/-dubbletter.
            urlPatterns: [/\/sv\/evenemang\/[^/]+\/?$/i],
            defaultCity: 'Stockholm',
        },
        updateFrequency: 'daily',
        notes: 'Probe 2026-06-08: 1424 event-URLs i sitemap-events.xml, JSON-LD @type=Event + startDate per sida.',
        lastVerified: '2026-06-08',
    },
    {
        id: 'dansenshus',
        hostName: 'Dansens Hus',
        region: 'stockholm',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://dansenshus.se/sitemap-post-type-dh_event.xml',
            // /program/SLUG/ på svenska; blacklista engelska /en/program/-dubbletter.
            urlPatterns: [/\/program\/[^/]+\/?$/i],
            urlBlacklist: [/\/en\//i],
            defaultCity: 'Stockholm',
        },
        updateFrequency: 'daily',
        notes: 'Probe 2026-06-08: 1338 URLs i sitemap-post-type-dh_event.xml (sv + en).',
        lastVerified: '2026-06-08',
    },

    {
        id: 'uppsala',
        hostName: 'Destination Uppsala',
        region: 'uppsala',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.destinationuppsala.se',
            variant: 'wp-v2',
            defaultCity: 'Uppsala',
            fetchDetailPage: true,
            maxPages: 6,  // 300 events max — annars tar fetch-loopen 30+ min
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 1217 events totalt. fetchDetailPage cap=300 för rimlig körtid.',
    },
    {
        id: 'helsingborg',
        hostName: 'Helsingborgs Stad',
        region: 'helsingborg',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.helsingborg.se',
            variant: 'wp-v2',
            defaultCity: 'Helsingborg',
        },
        updateFrequency: 'daily',
        notes: 'Probe 2026-06: 369 events. wp/v2 + content-parser + _embed (image + terms).',
    },
    {
        id: 'ostersund',
        hostName: 'Visit Östersund',
        region: 'ostersund',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.visitostersund.se',
            variant: 'wp-v2',
            endpoint: '/wp-json/wp/v2/evenemang',
            defaultCity: 'Östersund',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 226 events. Svensk CPT + content-parser.',
    },
    {
        id: 'bastad',
        hostName: 'Båstad',
        region: 'bastad',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.bastad.com',
            variant: 'tribe',
        },
        updateFrequency: 'daily',
        notes: 'Probe 2026-06: 48 events. The Events Calendar (Tribe).',
    },
    {
        id: 'trelleborg',
        hostName: 'Trelleborgs Kommun',
        region: 'trelleborg',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.trelleborg.se',
            variant: 'wp-v2',
            defaultCity: 'Trelleborg',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 33 events. wp/v2 + content-parser.',
    },
    {
        id: 'lidingo',
        hostName: 'Lidingö Stad',
        region: 'lidingo',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.lidingo.se',
            variant: 'wp-v2',
            endpoint: '/wp-json/wp/v2/evenemang',
            defaultCity: 'Lidingö',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 18 events. Svensk CPT + content-parser.',
    },
    {
        id: 'orebro',
        hostName: 'Visit Örebro',
        region: 'orebro',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.visitorebro.se',
            variant: 'wp-v2',
            defaultCity: 'Örebro',
        },
        updateFrequency: 'weekly',
        notes: 'Probe 2026-06: 1 event. wp/v2 + content-parser.',
    },

    // ─── ADDITIONAL FROM 290-KOMMUN PROBE (2026-06-02) ───────────────────────

    {
        id: 'eslov',
        hostName: 'Eslövs Kommun',
        region: 'eslov',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.eslov.se',
            variant: 'wp-v2',
            defaultCity: 'Eslöv',
            fetchDetailPage: true,
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 141 events. fetchDetailPage extraherar datum från HTML.',
    },
    {
        id: 'alingsas',
        hostName: 'Alingsås Kommun',
        region: 'alingsas',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.alingsas.se',
            variant: 'wp-v2',
            defaultCity: 'Alingsås',
            fetchDetailPage: true,
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 108 events. fetchDetailPage.',
    },
    {
        id: 'tranas',
        hostName: 'Tranås Kommun',
        region: 'tranas',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.tranas.se',
            variant: 'wp-v2',
            defaultCity: 'Tranås',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 53 events.',
    },
    {
        id: 'norsjo',
        hostName: 'Norsjö Kommun',
        region: 'norsjo',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.norsjo.se',
            variant: 'tribe',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 47 events. The Events Calendar (Tribe) — guld!',
    },
    {
        id: 'hoor',
        hostName: 'Höörs Kommun',
        region: 'hoor',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.hoor.se',
            variant: 'wp-v2',
            defaultCity: 'Höör',
            fetchDetailPage: true,
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 23 events. fetchDetailPage.',
    },
    {
        id: 'horby',
        hostName: 'Hörby Kommun',
        region: 'horby',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.horby.se',
            variant: 'wp-v2',
            defaultCity: 'Hörby',
            fetchDetailPage: true,
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 21 events. fetchDetailPage.',
    },
    {
        id: 'tingsryd',
        hostName: 'Tingsryds Kommun',
        region: 'tingsryd',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.tingsryd.se',
            variant: 'wp-v2',
            defaultCity: 'Tingsryd',
            fetchDetailPage: true,
        },
        updateFrequency: 'every-3d',
        notes: 'Probe 2026-06: 15 events. fetchDetailPage.',
    },
    {
        id: 'sater',
        hostName: 'Säters Kommun',
        region: 'sater',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.sater.se',
            variant: 'wp-v2',
            defaultCity: 'Säter',
            fetchDetailPage: true,
        },
        updateFrequency: 'weekly',
        notes: 'Probe 2026-06: 5 events. fetchDetailPage.',
    },
    // ─── NEXT.JS-DATA KÄLLOR (storstäderna är Next.js SSR) ───────────────────

    {
        id: 'visit-stockholm',
        hostName: 'Visit Stockholm',
        region: 'stockholm',
        engine: 'nextjs-data',
        config: {
            urls: ['https://www.visitstockholm.com/events/'],
            defaultCity: 'Stockholm',
        },
        updateFrequency: 'daily',
        notes: 'Next.js __NEXT_DATA__ extraction — events i contentBlocks[].value.items.',
    },

    {
        id: 'goteborg-co',
        hostName: 'Göteborg & Co',
        region: 'goteborg',
        engine: 'nuxt-data',
        config: {
            urls: ['https://www.goteborg.com/en/events'],
            defaultCity: 'Göteborg',
        },
        updateFrequency: 'daily',
        notes: 'Nuxt 3 __NUXT_DATA__ (devalue-format) dereferensering.',
    },

    // ─── SITEVISION KÄLLOR (svenska kommun-CMS) ──────────────────────────────

    {
        id: 'malmo',
        hostName: 'Malmö Stad',
        region: 'malmo',
        engine: 'sitevision',
        config: {
            urls: ['https://malmo.se/evenemangskalender'],
            defaultCity: 'Malmö',
        },
        updateFrequency: 'daily',
        notes: 'SiteVision se.soleil.eventListingLocal.',
    },

    // SiteVision-källor från probe 2026-06-02 (31 träffar utöver Malmö, ~836 events totalt)
    {
        id: 'nykvarn',
        hostName: 'Nykvarn Kommun',
        region: 'nykvarn',
        engine: 'sitevision',
        config: { urls: ['https://www.nykvarn.se/uppleva-och-gora/evenemang'], defaultCity: 'Nykvarn' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'sigtuna',
        hostName: 'Sigtuna Kommun',
        region: 'sigtuna',
        engine: 'sitevision',
        config: { urls: ['https://www.sigtuna.se/evenemang'], defaultCity: 'Sigtuna' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'sundbyberg',
        hostName: 'Sundbyberg Kommun',
        region: 'sundbyberg',
        engine: 'sitevision',
        config: { urls: ['https://www.sundbyberg.se/uppleva-och-gora/evenemang'], defaultCity: 'Sundbyberg' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'taby',
        hostName: 'Täby Kommun',
        region: 'taby',
        engine: 'sitevision',
        config: { urls: ['https://www.taby.se/evenemang'], defaultCity: 'Täby' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'nynashamn',
        hostName: 'Nynäshamn Kommun',
        region: 'nynashamn',
        engine: 'sitevision',
        config: { urls: ['https://www.nynashamn.se/evenemang'], defaultCity: 'Nynäshamn' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'gnesta',
        hostName: 'Gnesta Kommun',
        region: 'gnesta',
        engine: 'sitevision',
        config: { urls: ['https://www.gnesta.se/evenemang'], defaultCity: 'Gnesta' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'vetlanda',
        hostName: 'Vetlanda Kommun',
        region: 'vetlanda',
        engine: 'sitevision',
        config: { urls: ['https://www.vetlanda.se/uppleva-och-gora/evenemangskalender'], defaultCity: 'Vetlanda' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'ljungby',
        hostName: 'Ljungby Kommun',
        region: 'ljungby',
        engine: 'sitevision',
        config: { urls: ['https://www.ljungby.se/uppleva-och-gora/evenemangskalender'], defaultCity: 'Ljungby' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'uppvidinge',
        hostName: 'Uppvidinge Kommun',
        region: 'uppvidinge',
        engine: 'sitevision',
        config: { urls: ['https://www.uppvidinge.se/uppleva-och-gora/evenemang'], defaultCity: 'Uppvidinge' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'lessebo',
        hostName: 'Lessebo Kommun',
        region: 'lessebo',
        engine: 'sitevision',
        config: { urls: ['https://www.lessebo.se/evenemang'], defaultCity: 'Lessebo' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'kalmar-stad',
        hostName: 'Kalmar Kommun',
        region: 'kalmar',
        engine: 'sitevision',
        config: { urls: ['https://www.kalmar.se/evenemang'], defaultCity: 'Kalmar' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'gotland-kommun',
        hostName: 'Gotland Kommun',
        region: 'gotland',
        engine: 'sitevision',
        config: { urls: ['https://www.gotland.se/evenemang'], defaultCity: 'Gotland' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'klippan',
        hostName: 'Klippan Kommun',
        region: 'klippan',
        engine: 'sitevision',
        config: { urls: ['https://www.klippan.se/evenemang'], defaultCity: 'Klippan' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'ostra-goinge',
        hostName: 'Östra Göinge Kommun',
        region: 'ostra-goinge',
        engine: 'sitevision',
        config: { urls: ['https://www.ostragoinge.se/uppleva-och-gora/evenemang'], defaultCity: 'Östra Göinge' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'bengtsfors',
        hostName: 'Bengtsfors Kommun',
        region: 'bengtsfors',
        engine: 'sitevision',
        config: { urls: ['https://www.bengtsfors.se/uppleva-och-gora/evenemang'], defaultCity: 'Bengtsfors' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'herrljunga',
        hostName: 'Herrljunga Kommun',
        region: 'herrljunga',
        engine: 'sitevision',
        config: { urls: ['https://www.herrljunga.se/uppleva-och-gora/evenemang'], defaultCity: 'Herrljunga' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'lysekil',
        hostName: 'Lysekil Kommun',
        region: 'lysekil',
        engine: 'sitevision',
        config: { urls: ['https://www.lysekil.se/kalender'], defaultCity: 'Lysekil' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'molndal',
        hostName: 'Mölndal Kommun',
        region: 'molndal',
        engine: 'sitevision',
        config: { urls: ['https://www.molndal.se/uppleva-och-gora/evenemang'], defaultCity: 'Mölndal' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'svenljunga',
        hostName: 'Svenljunga Kommun',
        region: 'svenljunga',
        engine: 'sitevision',
        config: { urls: ['https://www.svenljunga.se/evenemangskalender'], defaultCity: 'Svenljunga' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'tranemo',
        hostName: 'Tranemo Kommun',
        region: 'tranemo',
        engine: 'sitevision',
        config: { urls: ['https://www.tranemo.se/kalender'], defaultCity: 'Tranemo' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'vargarda',
        hostName: 'Vårgårda Kommun',
        region: 'vargarda',
        engine: 'sitevision',
        config: { urls: ['https://www.vargarda.se/evenemang'], defaultCity: 'Vårgårda' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'forshaga',
        hostName: 'Forshaga Kommun',
        region: 'forshaga',
        engine: 'sitevision',
        config: { urls: ['https://www.forshaga.se/evenemang'], defaultCity: 'Forshaga' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'hammaro',
        hostName: 'Hammarö Kommun',
        region: 'hammaro',
        engine: 'sitevision',
        config: { urls: ['https://www.hammaro.se/uppleva-och-gora/evenemang'], defaultCity: 'Hammarö' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'kil',
        hostName: 'Kil Kommun',
        region: 'kil',
        engine: 'sitevision',
        config: { urls: ['https://www.kil.se/kalender'], defaultCity: 'Kil' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'fagersta',
        hostName: 'Fagersta Kommun',
        region: 'fagersta',
        engine: 'sitevision',
        config: { urls: ['https://www.fagersta.se/evenemang'], defaultCity: 'Fagersta' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'ljusnarsberg',
        hostName: 'Ljusnarsberg Kommun',
        region: 'ljusnarsberg',
        engine: 'sitevision',
        config: { urls: ['https://www.ljusnarsberg.se/evenemang'], defaultCity: 'Ljusnarsberg' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'borlange-stad',
        hostName: 'Borlänge Kommun',
        region: 'borlange',
        engine: 'sitevision',
        config: { urls: ['https://www.borlange.se/evenemang'], defaultCity: 'Borlänge' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'malung-salen',
        hostName: 'Malung-Sälen Kommun',
        region: 'malung-salen',
        engine: 'sitevision',
        config: { urls: ['https://www.malung-salen.se/evenemang'], defaultCity: 'Malung-Sälen' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'sandviken',
        hostName: 'Sandviken Kommun',
        region: 'sandviken',
        engine: 'sitevision',
        config: { urls: ['https://www.sandviken.se/evenemang'], defaultCity: 'Sandviken' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'stromsund',
        hostName: 'Strömsund Kommun',
        region: 'stromsund',
        engine: 'sitevision',
        config: { urls: ['https://www.stromsund.se/evenemang'], defaultCity: 'Strömsund' },
        updateFrequency: 'every-3d',
    },
    {
        id: 'haparanda',
        hostName: 'Haparanda Kommun',
        region: 'haparanda',
        engine: 'sitevision',
        config: { urls: ['https://www.haparanda.se/evenemang'], defaultCity: 'Haparanda' },
        updateFrequency: 'every-3d',
    },

    {
        id: 'staffanstorp',
        hostName: 'Staffanstorps Kommun',
        region: 'staffanstorp',
        engine: 'wp-rest',
        config: {
            baseUrl: 'https://www.staffanstorp.se',
            variant: 'wp-v2',
            defaultCity: 'Staffanstorp',
        },
        updateFrequency: 'weekly',
        notes: 'Probe 2026-06: 0 events vid probe (men endpoint finns). Kollar veckovis ifall de fyller på.',
    },

    // ─── SITEMAP-KÄLLOR (probe-sitemap 2026-06-03) ──────────────────────────
    // Discovery via /sitemap.xml. Datum extraheras via JSON-LD/microdata
    // när det finns, annars svensk text-parser. URL-blacklist (default i
    // engine) skippar protokoll/nämnd-möten som ligger i samma kalender.

    {
        id: 'motala',
        hostName: 'Motala Kommun',
        region: 'motala',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.motala.se/sitemap_index.xml',
            urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
            defaultCity: 'Motala',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-03: 131 aktivitet-URLs. Text-parser hittar datum i body.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'linkoping',
        hostName: 'Visit Linköping',
        region: 'linkoping',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.visitlinkoping.se/sitemap.xml',
            urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
            defaultCity: 'Linköping',
        },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-03: 187 evenemang-URLs. <time datetime> finns.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'morbylanga',
        hostName: 'Mörbylånga Kommun',
        region: 'morbylanga',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.morbylanga.se/sitemap.xml',
            urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
            defaultCity: 'Mörbylånga',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-03: 12 aktivitet-URLs. microdata startDate.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'monsteras',
        hostName: 'Mönsterås Kommun',
        region: 'monsteras',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.monsteras.se/sitemap.xml',
            urlPatterns: [/\/event\/[^/]+\/?$/i],
            defaultCity: 'Mönsterås',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-03: 649 event-URLs. Text-parser ur #event-dates-list.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'landskrona',
        hostName: 'Landskrona Stad',
        region: 'landskrona',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.landskrona.se/sitemap.xml',
            urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
            defaultCity: 'Landskrona',
        },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-03: 180 evenemang-URLs. <time datetime>.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'karlsborg',
        hostName: 'Karlsborg Kommun',
        region: 'karlsborg',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.karlsborg.se/sitemap.xml',
            urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
            defaultCity: 'Karlsborg',
        },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-03: 15 aktivitet-URLs. Text-parser.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'arjeplog',
        hostName: 'Arjeplog Kommun',
        region: 'arjeplog',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.arjeplog.se/sitemap.xml',
            urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
            defaultCity: 'Arjeplog',
        },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-03: 7 evenemang-URLs. Text-parser.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'jokkmokk',
        hostName: 'Jokkmokks Kommun',
        region: 'jokkmokk',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.jokkmokk.se/sitemap.xml',
            urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
            defaultCity: 'Jokkmokk',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-03: 463 evenemang-URLs. Text-parser. OBS: många historiska — runner-fönster filtrerar.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'pitea',
        hostName: 'Piteå Kommun',
        region: 'pitea',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.pitea.se/sitemap.xml',
            urlPatterns: [/\/Upplev\/Evenemang\/[^/]+\/?$/i],
            defaultCity: 'Piteå',
        },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-03: 17 evenemang-URLs. Text-parser.',
        lastVerified: '2026-06-04',
    },
    {
        id: 'dorotea',
        hostName: 'Dorotea Kommun',
        region: 'dorotea',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.dorotea.se/sitemap.xml',
            urlPatterns: [/\/kalender\/[^/]+\/?$/i],
            defaultCity: 'Dorotea',
        },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-03: 10 kalender-URLs. Text-parser. Liten kommun, sparsam volym.',
        lastVerified: '2026-06-04',
    },

    // ─── NATIONELLA KÄLLOR (täcker flera kommuner från en endpoint) ─────────
    // Studiefrämjandet publicerar event från hela Sverige under
    // /<län>/<förbund>/kalenderhandelser/<år>/<månad>/<slug>/. urlDateRegex
    // pre-filtrerar till veckans fönster utan att fetcha tusentals historiska
    // sidor. 1500+ event-URLs totalt → ~30-50 per vecka.
    {
        id: 'studieframjandet',
        hostName: 'Studiefrämjandet',
        region: 'national',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.studieframjandet.se/sitemap.xml',
            urlPatterns: [/\/kalenderhandelser\/\d{4}\/\w+\/[^/]+\/?$/i],
            urlDateRegex: /\/(?<year>\d{4})\/(?<month>\w+)\//,
            maxUrls: 300,
        },
        updateFrequency: 'daily',
        notes: 'Probe 2026-06-04: 1545 kalenderhandelser-URLs. urlDateRegex pre-filtrerar veckan FÖRE fetch.',
        lastVerified: '2026-06-04',
    },

    // Bilda — studieförbund med kursdatabas på /arr/<id>/<slug>/. Detaljsidan
    // har `<dt>Start</dt><dd>YYYY-MM-DD</dd>` som text-parser plockar via
    // ISO-mönster. 494 arrangemang i sitemap, riktiga datum för framtida event.
    {
        id: 'bilda',
        hostName: 'Bilda',
        region: 'national',
        engine: 'sitemap',
        config: {
            sitemapUrl: 'https://www.bilda.nu/arr-sitemap.xml',
            urlPatterns: [/\/arr\/\d+\/[^/]+\/?$/i],
            maxUrls: 300,
        },
        updateFrequency: 'daily',
        notes: 'Probe 2026-06-04: 494 arr-URLs. Text-parser ur HTML <dd>YYYY-MM-DD</dd>.',
        lastVerified: '2026-06-04',
    },

    // ─── SITEMAP-KÄLLOR PROBE 2026-06-04 (med gzip-stöd) ──────────────────────
    // 38 nya kommun-sajter funna via probe-sitemap efter att vi lagt in
    // gzip-stöd för komprimerade sitemap1.xml.gz-filer. Sorterade på volym.
    // URL-blacklist (default i engine) skippar kommunala möten/protokoll.
    {
        id: 'nykoping',
        hostName: 'Nyköping Kommun',
        region: 'nykoping',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.nykoping.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?kalender\/[^/]+\/?$/i],
                    defaultCity: 'Nyköping',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 2404 event-URLs (kalender-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'svalov',
        hostName: 'Svalöv Kommun',
        region: 'svalov',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.svalov.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Svalöv',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 1183 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'jonkoping',
        hostName: 'Jönköping Kommun',
        region: 'jonkoping',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.jonkoping.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Jönköping',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 925 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'mora',
        hostName: 'Mora Kommun',
        region: 'mora',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.visitdalarna.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Mora',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 904 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'goteborg',
        hostName: 'Göteborg Kommun',
        region: 'goteborg',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.goteborg.com/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Göteborg',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 594 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'saffle',
        hostName: 'Säffle Kommun',
        region: 'saffle',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.saffle.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Säffle',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 554 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'sodertalje',
        hostName: 'Södertälje Kommun',
        region: 'sodertalje',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.sodertalje.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Södertälje',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 316 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'falkenberg',
        hostName: 'Falkenberg Kommun',
        region: 'falkenberg',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.falkenberg.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Falkenberg',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 287 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'katrineholm',
        hostName: 'Katrineholm Kommun',
        region: 'katrineholm',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.katrineholm.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Katrineholm',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 286 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'robertsfors',
        hostName: 'Robertsfors Kommun',
        region: 'robertsfors',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.robertsfors.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Robertsfors',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 285 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'krokom',
        hostName: 'Krokom Kommun',
        region: 'krokom',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.krokom.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Krokom',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 266 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'nassjo',
        hostName: 'Nässjö Kommun',
        region: 'nassjo',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.nassjo.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Nässjö',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 253 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'upplands-vasby',
        hostName: 'Upplands Väsby Kommun',
        region: 'upplands-vasby',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://upplandsvasby.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Upplands Väsby',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 244 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'alvdalen',
        hostName: 'Älvdalen Kommun',
        region: 'alvdalen',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.alvdalen.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Älvdalen',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 231 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'arvidsjaur',
        hostName: 'Arvidsjaur Kommun',
        region: 'arvidsjaur',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.arvidsjaur.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Arvidsjaur',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 226 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'solvesborg',
        hostName: 'Sölvesborg Kommun',
        region: 'solvesborg',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.solvesborg.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Sölvesborg',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 212 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'bollnas',
        hostName: 'Bollnäs Kommun',
        region: 'bollnas',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://bollnas.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Bollnäs',
                },
        updateFrequency: 'daily',
        notes: 'Probe-sitemap 2026-06-04: 210 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'hedemora',
        hostName: 'Hedemora Kommun',
        region: 'hedemora',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.hedemora.se/sitemap_index.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Hedemora',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 170 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'orsa',
        hostName: 'Orsa Kommun',
        region: 'orsa',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.orsa.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Orsa',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 168 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'hoganas',
        hostName: 'Höganäs Kommun',
        region: 'hoganas',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.hoganas.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Höganäs',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 166 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'ale',
        hostName: 'Ale Kommun',
        region: 'ale',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.ale.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Ale',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 157 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'osby',
        hostName: 'Osby Kommun',
        region: 'osby',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.osby.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Osby',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 118 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'savsjo',
        hostName: 'Sävsjö Kommun',
        region: 'savsjo',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.savsjo.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Sävsjö',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 107 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'ystad',
        hostName: 'Ystad Kommun',
        region: 'ystad',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.ystad.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Ystad',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 107 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'karlstad',
        hostName: 'Karlstad Kommun',
        region: 'karlstad',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://karlstad.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?kalender\/[^/]+\/?$/i],
                    defaultCity: 'Karlstad',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 103 event-URLs (kalender-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'uddevalla',
        hostName: 'Uddevalla Kommun',
        region: 'uddevalla',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://uddevalla.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?event\/[^/]+\/?$/i],
                    defaultCity: 'Uddevalla',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 100 event-URLs (event-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'skelleftea',
        hostName: 'Skellefteå Kommun',
        region: 'skelleftea',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.skelleftea.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Skellefteå',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 95 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'angelholm',
        hostName: 'Ängelholm Kommun',
        region: 'angelholm',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.engelholm.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Ängelholm',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 92 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'upplands-bro',
        hostName: 'Upplands-Bro Kommun',
        region: 'upplands-bro',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.upplands-bro.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Upplands-Bro',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 79 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'asele',
        hostName: 'Åsele Kommun',
        region: 'asele',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.asele.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Åsele',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 69 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'vingaker',
        hostName: 'Vingåker Kommun',
        region: 'vingaker',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.vingaker.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?kalender\/[^/]+\/?$/i],
                    defaultCity: 'Vingåker',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 66 event-URLs (kalender-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'tyreso',
        hostName: 'Tyresö Kommun',
        region: 'tyreso',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.tyreso.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Tyresö',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 53 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'mullsjo',
        hostName: 'Mullsjö Kommun',
        region: 'mullsjo',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://mullsjo.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Mullsjö',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 53 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'gotland',
        hostName: 'Gotland Kommun',
        region: 'gotland',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.gotland.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Gotland',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 53 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'emmaboda',
        hostName: 'Emmaboda Kommun',
        region: 'emmaboda',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.emmaboda.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Emmaboda',
                },
        updateFrequency: 'every-3d',
        notes: 'Probe-sitemap 2026-06-04: 50 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'leksand',
        hostName: 'Leksand Kommun',
        region: 'leksand',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.leksand.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Leksand',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 44 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'halmstad',
        hostName: 'Halmstad Kommun',
        region: 'halmstad',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.destinationhalmstad.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Halmstad',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 41 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'bjurholm',
        hostName: 'Bjurholm Kommun',
        region: 'bjurholm',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.bjurholm.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Bjurholm',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 32 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },

    // ─── SITEMAP-KÄLLOR PROBE 2026-06-04 (lägre tröskel min=5) ──────────────
    // 30 till mindre kommuner. URL-blacklist + title-blacklist hindrar
    // falska positiva (cookie-banners, parkeringsavstängningar etc).
    {
        id: 'amal',
        hostName: 'Åmål Kommun',
        region: 'amal',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.amal.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Åmål',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 29 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'alvkarleby',
        hostName: 'Älvkarleby Kommun',
        region: 'alvkarleby',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.alvkarleby.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Älvkarleby',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 23 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'boras',
        hostName: 'Borås Kommun',
        region: 'boras',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.boras.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Borås',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 23 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'falkoping',
        hostName: 'Falköping Kommun',
        region: 'falkoping',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://falkoping.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?kalender\/[^/]+\/?$/i],
                    defaultCity: 'Falköping',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 22 event-URLs (kalender-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'nacka',
        hostName: 'Nacka Kommun',
        region: 'nacka',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.nacka.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Nacka',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 21 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'ockero',
        hostName: 'Öckerö Kommun',
        region: 'ockero',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.ockero.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Öckerö',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 21 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'kalmar',
        hostName: 'Kalmar Kommun',
        region: 'kalmar',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.kalmar.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Kalmar',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 19 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'skara',
        hostName: 'Skara Kommun',
        region: 'skara',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.skara.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Skara',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 19 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'hallsberg',
        hostName: 'Hallsberg Kommun',
        region: 'hallsberg',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.hallsberg.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Hallsberg',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 19 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'falun',
        hostName: 'Falun Kommun',
        region: 'falun',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.falun.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Falun',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 19 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'gislaved',
        hostName: 'Gislaved Kommun',
        region: 'gislaved',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://gislaved.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Gislaved',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 18 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'kristianstad',
        hostName: 'Kristianstad Kommun',
        region: 'kristianstad',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.kristianstad.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Kristianstad',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 14 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'enkoping',
        hostName: 'Enköping Kommun',
        region: 'enkoping',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://enkoping.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Enköping',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 12 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'habo',
        hostName: 'Habo Kommun',
        region: 'habo',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.habokommun.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?kalender\/[^/]+\/?$/i],
                    defaultCity: 'Habo',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 12 event-URLs (kalender-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'almhult',
        hostName: 'Älmhult Kommun',
        region: 'almhult',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.almhult.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Älmhult',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 12 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'stromstad',
        hostName: 'Strömstad Kommun',
        region: 'stromstad',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.stromstad.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Strömstad',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 12 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'karlskoga',
        hostName: 'Karlskoga Kommun',
        region: 'karlskoga',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.karlskoga.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Karlskoga',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 12 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'tanum',
        hostName: 'Tanum Kommun',
        region: 'tanum',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.tanum.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Tanum',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 11 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'rattvik',
        hostName: 'Rättvik Kommun',
        region: 'rattvik',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.rattvik.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Rättvik',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 10 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'borlange',
        hostName: 'Borlänge Kommun',
        region: 'borlange',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.borlange.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Borlänge',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 9 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'eksjo',
        hostName: 'Eksjö Kommun',
        region: 'eksjo',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.eksjo.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Eksjö',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 8 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'tjorn',
        hostName: 'Tjörn Kommun',
        region: 'tjorn',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://tjorn.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Tjörn',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 8 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'solleftea',
        hostName: 'Sollefteå Kommun',
        region: 'solleftea',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.solleftea.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Sollefteå',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 8 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'heby',
        hostName: 'Heby Kommun',
        region: 'heby',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.heby.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Heby',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 6 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'gotene',
        hostName: 'Götene Kommun',
        region: 'gotene',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.gotene.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Götene',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 6 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'lidkoping',
        hostName: 'Lidköping Kommun',
        region: 'lidkoping',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.lidkoping.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Lidköping',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 6 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'harjedalen',
        hostName: 'Härjedalen Kommun',
        region: 'harjedalen',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.herjedalen.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Härjedalen',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 6 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'lulea',
        hostName: 'Luleå Kommun',
        region: 'lulea',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.lulea.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Luleå',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 6 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'nybro',
        hostName: 'Nybro Kommun',
        region: 'nybro',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.nybro.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Nybro',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 5 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'soderhamn',
        hostName: 'Söderhamn Kommun',
        region: 'soderhamn',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.soderhamn.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Söderhamn',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 5 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },

    // ─── SITEMAP-KÄLLOR PROBE 2026-06-04 (svag tröskel min=2) ──────────────
    // 22 till stora/medel-städer som har sparse sitemap-event (2-4 URLs):
    // Växjö, Västerås, Sundsvall, Karlskrona, Kiruna, Norrtälje, Ronneby m.fl.
    // Få events men viktig täckning.
    {
        id: 'salem',
        hostName: 'Salem Kommun',
        region: 'salem',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.salem.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?arrangemang\/[^/]+\/?$/i],
                    defaultCity: 'Salem',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 4 event-URLs (arrangemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'olofstrom',
        hostName: 'Olofström Kommun',
        region: 'olofstrom',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.olofstrom.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Olofström',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 4 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'tomelilla',
        hostName: 'Tomelilla Kommun',
        region: 'tomelilla',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.tomelilla.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Tomelilla',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 4 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'arvika',
        hostName: 'Arvika Kommun',
        region: 'arvika',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.arvika.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?event\/[^/]+\/?$/i],
                    defaultCity: 'Arvika',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 4 event-URLs (event-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'vanersborg',
        hostName: 'Vänersborg Kommun',
        region: 'vanersborg',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.vanersborg.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Vänersborg',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 4 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'sunne',
        hostName: 'Sunne Kommun',
        region: 'sunne',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.sunne.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Sunne',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 4 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'vasteras',
        hostName: 'Västerås Kommun',
        region: 'vasteras',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://vasteras.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?kalender\/[^/]+\/?$/i],
                    defaultCity: 'Västerås',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 4 event-URLs (kalender-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'tierp',
        hostName: 'Tierp Kommun',
        region: 'tierp',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.tierp.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Tierp',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 3 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'karlskrona',
        hostName: 'Karlskrona Kommun',
        region: 'karlskrona',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.karlskrona.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?aktivitet(?:er)?\/[^/]+\/?$/i],
                    defaultCity: 'Karlskrona',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 3 event-URLs (aktivitet-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'partille',
        hostName: 'Partille Kommun',
        region: 'partille',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.partille.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Partille',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 3 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'berg',
        hostName: 'Berg Kommun',
        region: 'berg',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.berg.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?events\/[^/]+\/?$/i],
                    defaultCity: 'Berg',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 3 event-URLs (events-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'kiruna',
        hostName: 'Kiruna Kommun',
        region: 'kiruna',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://kiruna.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Kiruna',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 3 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'norrtalje',
        hostName: 'Norrtälje Kommun',
        region: 'norrtalje',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.norrtalje.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Norrtälje',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'vaxholm',
        hostName: 'Vaxholm Kommun',
        region: 'vaxholm',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.vaxholm.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Vaxholm',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'vaxjo',
        hostName: 'Växjö Kommun',
        region: 'vaxjo',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.vaxjo.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Växjö',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'alvesta',
        hostName: 'Alvesta Kommun',
        region: 'alvesta',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.alvesta.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Alvesta',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'karlshamn',
        hostName: 'Karlshamn Kommun',
        region: 'karlshamn',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.karlshamn.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Karlshamn',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'ronneby',
        hostName: 'Ronneby Kommun',
        region: 'ronneby',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.ronneby.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?kalender\/[^/]+\/?$/i],
                    defaultCity: 'Ronneby',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (kalender-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'orkelljunga',
        hostName: 'Örkelljunga Kommun',
        region: 'orkelljunga',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.orkelljunga.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Örkelljunga',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'vara',
        hostName: 'Vara Kommun',
        region: 'vara',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.vara.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Vara',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'kramfors',
        hostName: 'Kramfors Kommun',
        region: 'kramfors',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.kramfors.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Kramfors',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
    {
        id: 'sundsvall',
        hostName: 'Sundsvall Kommun',
        region: 'sundsvall',
        engine: 'sitemap',
        config: {
                    sitemapUrl: 'https://www.sundsvall.se/sitemap.xml',
                    urlPatterns: [/\/(?:sv\/)?evenemang\/[^/]+\/?$/i],
                    defaultCity: 'Sundsvall',
                },
        updateFrequency: 'weekly',
        notes: 'Probe-sitemap 2026-06-04: 2 event-URLs (evenemang-mönster).',
        lastVerified: '2026-06-04',
    },
];

/**
 * Filtrera registry på id-prefix eller region — användbart för debugging:
 *   const stockholm = filterSources({ region: 'stockholm' });
 */
export function filterSources(opts: { id?: string; region?: string; engine?: string }): Source[] {
    return SOURCES.filter((s) => {
        if (opts.id && !s.id.includes(opts.id)) return false;
        if (opts.region && s.region !== opts.region) return false;
        if (opts.engine && s.engine !== opts.engine) return false;
        return true;
    });
}
