/**
 * GENERERAD FIL — webb-snöbollens auto-upptäckta källor.
 *
 * Pipeline (scripts/web-snowball.ts, veckokörning tis 09:00 via launchd):
 *   1. Skörda kandidat-domäner ur eventdatan (länkar i beskrivningar +
 *      slug-gissningar för återkommande arrangörer utan känd domän).
 *   2. bulk-probe verifierar strukturerad eventdata (Tribe/wp-v2/sitemap).
 *   3. Smoke-test: motorn körs på riktigt (utan DB-skrivning) och eventen
 *      rimlighetskontrolleras (antal, datum, titelkvalitet, Sverige-signal).
 *   4. Bara godkända kandidater skrivs hit, som status 'experimental'.
 *
 * Skyddsnät efteråt: nattkedjans AI-audit + hide-junk + auto-karantänen
 * (4 raka tomma körningar ⇒ paus). Redigera hellre kurerade källor i
 * registry.ts — denna fil skrivs över av snöbollen.
 */

import { Source } from './types';

export const SNOWBALL_SOURCES: Source[] = [

    {
        id: 'sb-visitpitea-se',
        hostName: 'Visit Piteå',
        region: 'pitea',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://visitpitea.se', variant: 'wp-v2', defaultCity: 'Piteå', fetchDetailPage: true, maxPages: 5 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitpitea.se',
            date: '2026-08-19',
            rawEventCount: 50,
        },
        notes: 'web-snöboll 2026-08-19: wp-v2, smoke 50 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-19',
    },
    {
        id: 'sb-visitsundsvall-se',
        hostName: 'Visit Sundsvall',
        region: 'sundsvall',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitsundsvall.se/destination/evenemang"], defaultCity: 'Sundsvall' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitsundsvall.se/destination/evenemang',
            date: '2026-08-19',
            rawEventCount: 4,
        },
        notes: 'web-snöboll 2026-08-19: sitevision-cal, smoke 4 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-19',
    },

    {
        id: 'sb-gamlalinkoping-info',
        hostName: 'Gamla Linköping',
        region: 'linkoping',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://gamlalinkoping.info', variant: 'wp-v2', defaultCity: 'Linköping', fetchDetailPage: true, maxPages: 5 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://gamlalinkoping.info',
            date: '2026-08-20',
            rawEventCount: 13,
        },
        notes: 'web-snöboll 2026-08-20: wp-v2, smoke 13 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-20',
    },
    {
        id: 'sb-linkopingsstadsfest-se',
        hostName: 'Linköpings Stadsfest',
        region: 'linkoping',
        engine: 'sitemap' as const,
        config: { sitemapUrl: 'https://linkopingsstadsfest.se/sitemap.xml', urlPatterns: [/\/evenemang\/[a-z0-9][a-z0-9-]{2,}/i], defaultCity: 'Linköping', maxUrls: 200 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://linkopingsstadsfest.se/sitemap.xml',
            date: '2026-08-20',
            rawEventCount: 51,
        },
        notes: 'web-snöboll 2026-08-20: sitemap-text, smoke 51 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-20',
    },

    {
        id: 'sb-regionostergotland-se',
        hostName: 'Region Östergötland',
        region: 'ostergotland',
        engine: 'sitemap' as const,
        config: { sitemapUrl: 'https://www.regionostergotland.se/rest-api/sitemap/4.32669883183822752aa905', urlPatterns: [/\/kalender\/[a-z0-9][a-z0-9-]{2,}/i], defaultCity: '', maxUrls: 200 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.regionostergotland.se/rest-api/sitemap/4.32669883183822752aa905',
            date: '2026-08-20',
            rawEventCount: 3,
        },
        notes: 'web-snöboll 2026-08-20: sitemap-text, smoke 3 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-20',
    },

    {
        id: 'sb-ulricehamn-se',
        hostName: 'Ulricehamn Kommun',
        region: 'ulricehamn',
        engine: 'sitevision' as const,
        config: { urls: ["https://www.ulricehamn.se/arkiv/kalender"], defaultCity: 'Ulricehamn' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.ulricehamn.se/arkiv/kalender',
            date: '2026-08-23',
            rawEventCount: 10,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 10 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-norberg-se',
        hostName: 'Norberg Kommun',
        region: 'norberg',
        engine: 'sitevision' as const,
        config: { urls: ["https://www.norberg.se/visitnorberg/visit-norberg"], defaultCity: 'Norberg' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.norberg.se/visitnorberg/visit-norberg',
            date: '2026-08-23',
            rawEventCount: 4,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 4 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-surahammar-se',
        hostName: 'Surahammar Kommun',
        region: 'surahammar',
        engine: 'sitevision' as const,
        config: { urls: ["https://www.surahammar.se/download/18.11ab9bc018b6ab78ed33df3"], defaultCity: 'Surahammar', restApi: {"url":"https://www.surahammar.se/rest-api/Evenemang"} },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.surahammar.se/download/18.11ab9bc018b6ab78ed33df3',
            date: '2026-08-23',
            rawEventCount: 36,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-restapp, smoke 36 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-gagnef-se',
        hostName: 'Gagnef Kommun',
        region: 'gagnef',
        engine: 'sitemap' as const,
        config: { sitemapUrl: 'https://www.gagnef.se/gagnef-event-sitemap.xml', urlPatterns: [/\/evenemang\/[a-z0-9][a-z0-9-]{2,}/i], defaultCity: 'Gagnef', maxUrls: 200 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.gagnef.se/gagnef-event-sitemap.xml',
            date: '2026-08-23',
            rawEventCount: 34,
        },
        notes: 'web-snöboll 2026-08-23: sitemap-text, smoke 34 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },

    {
        id: 'sb-jarfalla-se',
        hostName: 'Järfälla Kommun',
        region: 'jarfalla',
        engine: 'sitevision' as const,
        config: { urls: ["https://www.jarfalla.se/evenemang"], defaultCity: 'Järfälla' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.jarfalla.se/evenemang',
            date: '2026-08-23',
            rawEventCount: 121,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 121 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-ydre-se',
        hostName: 'Ydre Kommun',
        region: 'ydre',
        engine: 'sitevision' as const,
        config: { urls: ["https://www.ydre.se/destinationydre/evenemang"], defaultCity: 'Ydre' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.ydre.se/destinationydre/evenemang',
            date: '2026-08-23',
            rawEventCount: 11,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 11 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-varberg-se',
        hostName: 'Varberg Kommun',
        region: 'varberg',
        engine: 'sitevision' as const,
        config: { urls: ["https://www.varberg.se/kalender"], defaultCity: 'Varberg' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.varberg.se/kalender',
            date: '2026-08-23',
            rawEventCount: 148,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 148 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-askersund-se',
        hostName: 'Askersund Kommun',
        region: 'askersund',
        engine: 'sitevision' as const,
        config: { urls: ["https://www.askersund.se/evenemang"], defaultCity: 'Askersund' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.askersund.se/evenemang',
            date: '2026-08-23',
            rawEventCount: 5,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 5 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-lekeberg-se',
        hostName: 'Lekeberg Kommun',
        region: 'lekeberg',
        engine: 'sitevision' as const,
        config: { urls: ["https://www.lekeberg.se/upplevaochgora/evenemang.4.711bc06b14820d116bc33f4.html"], defaultCity: 'Lekeberg' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.lekeberg.se/upplevaochgora/evenemang.4.711bc06b14820d116bc33f4.html',
            date: '2026-08-23',
            rawEventCount: 4,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 4 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },

    {
        id: 'sb-visitknivsta-se',
        hostName: 'Visitknivsta',
        region: 'national',
        engine: 'sitemap' as const,
        config: { sitemapUrl: 'https://www.visitknivsta.se/ajde_events-sitemap.xml', urlPatterns: [/\/events\/[a-z0-9][a-z0-9-]{2,}/i], defaultCity: '', maxUrls: 200 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.visitknivsta.se/ajde_events-sitemap.xml',
            date: '2026-08-23',
            rawEventCount: 31,
        },
        notes: 'web-snöboll 2026-08-23: sitemap-json-ld, smoke 31 event ok. Slug-gissning från arrangör "undefined" (undefined event i DB).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitflen-se',
        hostName: 'Visit Flen',
        region: 'flen',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitflen.se/evenemang"], defaultCity: 'Flen' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitflen.se/evenemang',
            date: '2026-08-23',
            rawEventCount: 6,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 6 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitoxelosund-se',
        hostName: 'Visit Oxelösund',
        region: 'oxelosund',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitoxelosund.se/evenemang"], defaultCity: 'Oxelösund' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitoxelosund.se/evenemang',
            date: '2026-08-23',
            rawEventCount: 34,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 34 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-destinationfinspang-se',
        hostName: 'Visit Finspång',
        region: 'finspang',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://destinationfinspang.se', variant: 'tribe', defaultCity: 'Finspång', fetchDetailPage: false, maxPages: 4 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://destinationfinspang.se',
            date: '2026-08-23',
            rawEventCount: 47,
        },
        notes: 'web-snöboll 2026-08-23: tribe, smoke 47 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-upplevmotala-se',
        hostName: 'Visit Motala',
        region: 'motala',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://upplevmotala.se', variant: 'tribe', defaultCity: 'Motala', fetchDetailPage: false, maxPages: 4 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://upplevmotala.se',
            date: '2026-08-23',
            rawEventCount: 49,
        },
        notes: 'web-snöboll 2026-08-23: tribe, smoke 49 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitmullsjo-se',
        hostName: 'Visit Mullsjö',
        region: 'mullsjo',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitmullsjo.se/visit-mullsjo/evenemang"], defaultCity: 'Mullsjö' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitmullsjo.se/visit-mullsjo/evenemang',
            date: '2026-08-23',
            rawEventCount: 10,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 10 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitsavsjo-se',
        hostName: 'Visit Sävsjö',
        region: 'savsjo',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitsavsjo.se/turism/startsida"], defaultCity: 'Sävsjö' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitsavsjo.se/turism/startsida',
            date: '2026-08-23',
            rawEventCount: 6,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 6 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visithultsfred-se',
        hostName: 'Visit Hultsfred',
        region: 'hultsfred',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://visithultsfred.se', variant: 'tribe', defaultCity: 'Hultsfred', fetchDetailPage: false, maxPages: 4 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visithultsfred.se',
            date: '2026-08-23',
            rawEventCount: 48,
        },
        notes: 'web-snöboll 2026-08-23: tribe, smoke 48 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-upplevnybro-se',
        hostName: 'Visit Nybro',
        region: 'nybro',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://upplevnybro.se', variant: 'wp-v2', defaultCity: 'Nybro', fetchDetailPage: true, maxPages: 5, endpoint: '/wp-json/wp/v2/evenemang' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://upplevnybro.se',
            date: '2026-08-23',
            rawEventCount: 50,
        },
        notes: 'web-snöboll 2026-08-23: wp-v2, smoke 50 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitvimmerby-com',
        hostName: 'Visit Vimmerby',
        region: 'vimmerby',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://visitvimmerby.com', variant: 'tribe', defaultCity: 'Vimmerby', fetchDetailPage: false, maxPages: 4 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitvimmerby.com',
            date: '2026-08-23',
            rawEventCount: 42,
        },
        notes: 'web-snöboll 2026-08-23: tribe, smoke 42 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitbastad-se',
        hostName: 'Visit Båstad',
        region: 'bastad',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://visitbastad.se', variant: 'tribe', defaultCity: 'Båstad', fetchDetailPage: false, maxPages: 4 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitbastad.se',
            date: '2026-08-23',
            rawEventCount: 17,
        },
        notes: 'web-snöboll 2026-08-23: tribe, smoke 17 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitkristianstad-se',
        hostName: 'Visit Kristianstad',
        region: 'kristianstad',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitkristianstad.se/evenemang"], defaultCity: 'Kristianstad' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitkristianstad.se/evenemang',
            date: '2026-08-23',
            rawEventCount: 15,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 15 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitangelholm-se',
        hostName: 'Visit Ängelholm',
        region: 'angelholm',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://visitangelholm.se', variant: 'wp-v2', defaultCity: 'Ängelholm', fetchDetailPage: true, maxPages: 5 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitangelholm.se',
            date: '2026-08-23',
            rawEventCount: 45,
        },
        notes: 'web-snöboll 2026-08-23: wp-v2, smoke 45 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitlaholm-se',
        hostName: 'Visit Laholm',
        region: 'laholm',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitlaholm.se/evenemang/evenemangskalender"], defaultCity: 'Laholm' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitlaholm.se/evenemang/evenemangskalender',
            date: '2026-08-23',
            rawEventCount: 8,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 8 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitkumla-se',
        hostName: 'Visit Kumla',
        region: 'kumla',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitkumla.se/evenemang"], defaultCity: 'Kumla' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitkumla.se/evenemang',
            date: '2026-08-23',
            rawEventCount: 29,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 29 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitlindesberg-se',
        hostName: 'Visit Lindesberg',
        region: 'lindesberg',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitlindesberg.se/evenemang"], defaultCity: 'Lindesberg' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitlindesberg.se/evenemang',
            date: '2026-08-23',
            rawEventCount: 8,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 8 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitarboga-se',
        hostName: 'Visit Arboga',
        region: 'arboga',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitarboga.se/download/18.e8970c418b6ab9102db98b"], defaultCity: 'Arboga', restApi: {"url":"https://visitarboga.se/rest-api/Evenemang"} },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitarboga.se/download/18.e8970c418b6ab9102db98b',
            date: '2026-08-23',
            rawEventCount: 161,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-restapp, smoke 161 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitvilhelmina-com',
        hostName: 'Visitvilhelmina',
        region: 'national',
        engine: 'sitemap' as const,
        config: { sitemapUrl: 'https://visitvilhelmina.com/evenemang-sitemap.xml', urlPatterns: [/\/evenemang\/[a-z0-9][a-z0-9-]{2,}/i], defaultCity: '', maxUrls: 200 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitvilhelmina.com/evenemang-sitemap.xml',
            date: '2026-08-23',
            rawEventCount: 10,
        },
        notes: 'web-snöboll 2026-08-23: sitemap-text, smoke 10 event ok. Slug-gissning från arrangör "undefined" (undefined event i DB).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitgallivare-se',
        hostName: 'Visit Gällivare',
        region: 'gallivare',
        engine: 'sitevision' as const,
        config: { urls: ["https://visitgallivare.se/turismen/visit-gallivare"], defaultCity: 'Gällivare' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitgallivare.se/turismen/visit-gallivare',
            date: '2026-08-23',
            rawEventCount: 4,
        },
        notes: 'web-snöboll 2026-08-23: sitevision-cal, smoke 4 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-visitpajala-com',
        hostName: 'Visit Pajala',
        region: 'pajala',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://visitpajala.com', variant: 'tribe', defaultCity: 'Pajala', fetchDetailPage: false, maxPages: 4 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://visitpajala.com',
            date: '2026-08-23',
            rawEventCount: 5,
        },
        notes: 'web-snöboll 2026-08-23: tribe, smoke 5 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-destinationalvsbyn-se',
        hostName: 'Visit Älvsbyn',
        region: 'alvsbyn',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://destinationalvsbyn.se', variant: 'wp-v2', defaultCity: 'Älvsbyn', fetchDetailPage: true, maxPages: 5, endpoint: '/wp-json/wp/v2/events' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://destinationalvsbyn.se',
            date: '2026-08-23',
            rawEventCount: 8,
        },
        notes: 'web-snöboll 2026-08-23: wp-v2, smoke 8 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },
    {
        id: 'sb-vemdalen-se',
        hostName: 'Visit Vemdalen',
        region: 'harjedalen',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://www.vemdalen.se', variant: 'wp-v2', defaultCity: '', fetchDetailPage: true, maxPages: 5 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://www.vemdalen.se',
            date: '2026-08-23',
            rawEventCount: 46,
        },
        notes: 'web-snöboll 2026-08-23: wp-v2, smoke 46 event ok. Manuell kandidatlista (stads-svep).',
        lastVerified: '2026-08-23',
    },

    {
        id: 'sb-vastsverige-com',
        hostName: 'Vastsverige',
        region: 'national',
        engine: 'sitemap' as const,
        config: { sitemapUrl: 'https://vastsverige.com/sitemap.xml', urlPatterns: [/\/events\/[a-z0-9][a-z0-9-]{2,}/i], defaultCity: '', maxUrls: 200 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://vastsverige.com/sitemap.xml',
            date: '2026-08-25',
            rawEventCount: 6,
        },
        notes: 'web-snöboll 2026-08-25: sitemap-text, smoke 6 event ok. Hänvisad av 10 event i DB (t.ex. "Sommarkvällar i Helensparken - Spara och Slösa - Familjemusi").',
        lastVerified: '2026-08-25',
    },
    {
        id: 'sb-heptown-com',
        hostName: 'Heptown',
        region: 'national',
        engine: 'wp-rest' as const,
        config: { baseUrl: 'https://heptown.com', variant: 'tribe', defaultCity: '', fetchDetailPage: false, maxPages: 4 },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://heptown.com',
            date: '2026-08-25',
            rawEventCount: 27,
        },
        notes: 'web-snöboll 2026-08-25: tribe, smoke 27 event ok. Hänvisad av 6 event i DB (t.ex. "Monday Night Swing Pop-Up: Sommarlunds Dansbana + Unofficial").',
        lastVerified: '2026-08-25',
    },
    {
        id: 'sb-kb-se',
        hostName: 'Kb',
        region: 'national',
        engine: 'sitevision' as const,
        config: { urls: ["https://kb.se/om-oss/evenemang"], defaultCity: '' },
        updateFrequency: 'every-3d' as const,
        status: 'experimental' as const,
        discovery: {
            method: 'hint' as const,
            probeUrl: 'https://kb.se/om-oss/evenemang',
            date: '2026-08-25',
            rawEventCount: 5,
        },
        notes: 'web-snöboll 2026-08-25: sitevision-cal, smoke 5 event ok. Hänvisad av 3 event i DB (t.ex. "Visning av Roggebibliotekets samlingar").',
        lastVerified: '2026-08-25',
    },
];
